enum class TokenType(val pattern: String) {
    BLOCKCOMMENT("/\\*([^*]|[\\r\\n]|(\\*+([^*/]|[\\r\\n])))*\\*+/"),
    SINGLELINECOMMENT("//.*+"),

    WHITESPACE("\\s+"),

    DECIMAL("[+-]?([0-9]+[.])[0-9]+"),
    INTEGRAL("[+-]?[0-9]+"),

    TYPEALIAS("typealias\\b"),
    INTERFACE("interface\\b"),
    CONTINUE("continue\\b"),
    PACKAGE("package\\b"),
    IMPORT("import\\b"),
    RETURN("return\\b"),
    OBJECT("object\\b"),
    WHILE("while\\b"),
    BREAK("break\\b"),
    CLASS("class\\b"),
    THROW("throw\\b"),
    FALSE("false\\b"),
    SUPER("super\\b"),
    TYPEOF("typeof\\b"),
    WHEN("when\\b"),
    TRUE("true\\b"),
    THIS("this\\b"),
    NULL("null\\b"),
    ELSE("else\\b"),
    TRY("try\\b"),
    VAL("val\\b"),
    VAR("var\\b"),
    FUN("fun\\b"),
    FOR("for\\b"),
    IS("is\\b"),
    IN("in\\b"),
    IF("if\\b"),
    DO("do\\b"),
    AS("as\\b"),

    RESERVED("\\.\\.\\."),
    EQEQEQ("==="),
    EXCLEQEQ("!=="),
    NOTIN("!in\\s+"),
    NOTIS("!is\\s+"),
    ASSAFE("as\\?"),
    INCR("\\+\\+"),
    DECR("--"),
    LTEQ("<="),
    GTEQ(">="),
    DOUBLEEQ("=="),
    EXCLEQ("!="),
    ANDAND("&&"),
    OROR("\\|\\|"),
    MULTEQ("//*="),
    DIVEQ("/="),
    PEREQ("%/"),
    PLUSEQ("//+="),
    MINUSEQ("-="),
    ARROW("->"),
    DOUBLEARROW("=>"),
    RANGE("\\.\\."),
    COLONCOLON("::"),
    LBRACKET("\\["),
    RBRACKET("\\]"),
    LBRACE("\\{"),
    RBRACE("\\}"),
    LPAR("\\("),
    RPAR("\\)"),
    DOT("\\."),
    MUL("\\*"),
    PLUS("\\+"),
    MINUS("-"),
    EXCL("!"),
    DIV("/"),
    PERC("%"),
    LT("<"),
    GT(">"),
    QUEST("\\?"),
    COLON(":"),
    SEMICOLON(";"),
    EQ("="),
    COMMA(","),
    HASH("#"),
    AT("@"),
    DOLLAR("\\$"),
    BRACKETS("\\\""),

    ID("[a-zA-Z][a-zA-Z0-9_]*"),

    ERROR(".+")
}

data class Token(val tokenType: TokenType, val lexeme: String, val position: Position)

data class Position(val startIndex: Int, val endIndex: Int)